/**
 * Deterministic reaction-time e2e harness.
 *
 * This module powers the BUILD-GUARDED `/test-runtime` route (see `+page.ts`,
 * which 404s unless `import.meta.env.DEV` or `VITE_ENABLE_TEST_RUNTIME`). It
 * rebuilds — properly guarded — the `window.__QDESIGNER_RUNTIME_DEBUG__` surface
 * that was removed with the old unguarded dev route in commit 81bc0de.
 *
 * Design principle: reaction-time correctness is verified by INJECTED
 * deterministic timing, never by measuring real wall-clock latency (which
 * automation cannot reproduce frame-for-frame). The harness therefore exposes:
 *
 *   1. Seed-stable trial sequences generated by the *real* production preset
 *      builders (`createStroopTrials` / `createFlankerTrials` /
 *      `createNBackTrials`). These carry congruency, target flags and expected
 *      responses, so trial-count, congruency-ratio and seed-stability are all
 *      assertable without touching the GPU or the clock.
 *
 *   2. A synthetic timing injection API: a test supplies a stimulus-onset
 *      timestamp and a response timestamp, and the harness computes RT with the
 *      *exact* production formula (`computeReactionTimeMs`, the same function
 *      the runtime and ReactionEngine call). Asserting `rt === response - onset`
 *      therefore exercises real code.
 *
 *   3. A control-flow simulator that walks a fixture questionnaire's pages and
 *      flow rules using the real `VariableEngine` — mirroring
 *      `QuestionnaireRuntime.findMatchingFlowRule` / `evaluateVisibility` /
 *      `handleFlowControl` — so skip/branch logic is deterministic and does not
 *      depend on WebGL, module registration or key events.
 */

import {
  createStroopTrials,
  createFlankerTrials,
  createNBackTrials,
} from '$lib/runtime/reaction';
import { computeReactionTimeMs } from '$lib/runtime/core/reactionTiming';
import { VariableEngine } from '@qdesigner/scripting-engine';
import type { Variable, VariableType } from '@qdesigner/questionnaire-core';

export type ScenarioName = 'stroop' | 'flanker' | 'nback' | 'control-flow';

export interface TrialView {
  index: number;
  id: string;
  /** Present for stroop/flanker; the experimental condition of the trial. */
  congruency?: string;
  /** Key the participant should press for a correct response. */
  expectedResponse?: string;
  /** Present for n-back: whether this position is an n-back target. */
  isTarget?: boolean;
  /** Stroop-only descriptive fields. */
  word?: string;
  inkColor?: string;
  /** Flanker-only descriptive field. */
  displayString?: string;

  // Injected timing (null until a response is injected for this trial).
  stimulusOnsetTimestamp: number | null;
  responseTimestamp: number | null;
  reactionTimeMs: number | null;
  responseValue: string | null;
  /** null = no expectedResponse to compare against, else correctness. */
  correct: boolean | null;
}

export interface ControlFlowResult {
  presentedPageIds: string[];
  presentedQuestionIds: string[];
  skippedPageIds: string[];
}

export interface ScenarioOptions {
  seed?: string;
  trialCount?: number;
  /** control-flow only: map of `<questionId>` -> answer value. */
  answers?: Record<string, unknown>;
}

/** Serializable snapshot returned to Playwright via `page.evaluate`. */
export interface RuntimeDebugSnapshot {
  ready: boolean;
  scenario: ScenarioName;
  seed: string;
  trials: TrialView[];
  trialCount: number;
  currentTrialIndex: number;
  currentTrial: TrialView | null;
  stimulusOnsetTimestamp: number | null;
  responseTimestamp: number | null;
  reactionTimeMs: number | null;
  controlFlow: ControlFlowResult | null;
  completed: boolean;
  errors: string[];
}

export interface RuntimeDebugApi extends RuntimeDebugSnapshot {
  /** Rebuild the harness for a scenario/seed. Resets all injected timing. */
  loadScenario(name: ScenarioName, options?: ScenarioOptions): RuntimeDebugSnapshot;
  /** Record a synthetic stimulus-onset timestamp for a trial. */
  injectStimulusOnset(index: number, onsetTimestamp: number): void;
  /**
   * Record a synthetic response for a trial and compute its RT via the
   * production formula. Requires a prior `injectStimulusOnset` for the trial.
   */
  injectResponse(index: number, responseTimestamp: number, value?: string): TrialView;
  /** Convenience: onset + response in one call. */
  injectTrial(
    index: number,
    onsetTimestamp: number,
    responseTimestamp: number,
    value?: string
  ): TrialView;
  /** Advance the current-trial cursor; returns the new index. */
  advance(): number;
  /** Simulate page/flow control for the control-flow fixture. */
  runControlFlow(answers?: Record<string, unknown>): ControlFlowResult;
  /** Data-only snapshot (safe to return through page.evaluate). */
  snapshot(): RuntimeDebugSnapshot;
}

const DEFAULT_SEED = 'harness-seed';
const DEFAULT_TRIAL_COUNT = 12;

interface RuntimeWindow extends Window {
  __QDESIGNER_RUNTIME_DEBUG__?: RuntimeDebugApi;
}

// --- Control-flow fixture ----------------------------------------------------
// Mirrors the original `control-flow` scenario: three single-question pages and
// one skip rule that jumps p1 -> p3 when the gate answer equals 1.

interface FixturePage {
  id: string;
  questionIds: string[];
  /** Visibility conditions, same shape as runtime Page.conditions. */
  conditions?: Array<{ formula: string; target?: 'show' | 'hide' }>;
}

interface FixtureFlowRule {
  id: string;
  type: 'skip' | 'branch' | 'terminate';
  condition: string;
  target?: string;
}

interface ControlFlowFixture {
  pages: FixturePage[];
  flow: FixtureFlowRule[];
}

function buildControlFlowFixture(): ControlFlowFixture {
  return {
    pages: [
      { id: 'p1', questionIds: ['q_gate'] },
      { id: 'p2', questionIds: ['q_should_skip'] },
      { id: 'p3', questionIds: ['q_target'] },
    ],
    flow: [
      {
        id: 'skip_when_gate_yes',
        type: 'skip',
        condition: '(_currentPage == 1) and (q_gate_value == 1)',
        target: 'p3',
      },
    ],
  };
}

function inferVariableType(value: unknown): VariableType {
  if (typeof value === 'number') return 'number';
  if (typeof value === 'boolean') return 'boolean';
  return 'string';
}

/**
 * Faithful, GPU-free simulation of the runtime's page walk for the control-flow
 * fixture. Uses the real VariableEngine so the flow-rule conditions are
 * evaluated by the same mathjs-backed evaluator the runtime uses.
 */
function simulateControlFlow(
  fixture: ControlFlowFixture,
  answers: Record<string, unknown>
): ControlFlowResult {
  const engine = new VariableEngine();

  const register = (variable: Variable) => engine.registerVariable(variable);

  register({ id: '_currentPage', name: '_currentPage', type: 'number', scope: 'global', defaultValue: 0 });
  for (const [questionId, value] of Object.entries(answers)) {
    register({
      id: `${questionId}_value`,
      name: `${questionId}_value`,
      type: inferVariableType(value),
      scope: 'global',
      defaultValue: value,
    });
  }

  const pageIndexById = new Map(fixture.pages.map((page, index) => [page.id, index]));

  const evaluateVisibility = (page: FixturePage): boolean => {
    if (!page.conditions) return true;
    for (const condition of page.conditions) {
      if (!condition.formula) continue;
      const target = condition.target ?? 'show';
      const result = Boolean(engine.evaluateFormula(condition.formula).value);
      if (target === 'show' && !result) return false;
      if (target === 'hide' && result) return false;
    }
    return true;
  };

  const findMatchingFlowRule = (): FixtureFlowRule | null => {
    for (const rule of fixture.flow) {
      const result = Boolean(engine.evaluateFormula(rule.condition || 'true').value);
      if (result) return rule;
    }
    return null;
  };

  const presentedPageIds: string[] = [];
  const presentedQuestionIds: string[] = [];
  const skippedPageIds: string[] = [];

  let index = 0;
  let guard = 0;
  const maxSteps = fixture.pages.length * 4 + 8;

  while (index < fixture.pages.length && guard++ < maxSteps) {
    const page = fixture.pages[index]!;
    engine.setVariable('_currentPage', index + 1, 'system');

    if (!evaluateVisibility(page)) {
      skippedPageIds.push(page.id);
      index += 1;
      continue;
    }

    presentedPageIds.push(page.id);
    for (const questionId of page.questionIds) {
      presentedQuestionIds.push(questionId);
      // Answers were pre-registered; setting again is harmless but keeps the
      // walk explicit about when each response becomes visible to flow rules.
      if (questionId in answers) {
        engine.setVariable(`${questionId}_value`, answers[questionId], 'response');
      }
    }

    const rule = findMatchingFlowRule();
    if (rule) {
      if (rule.type === 'terminate') break;
      if ((rule.type === 'skip' || rule.type === 'branch') && rule.target) {
        const targetIndex = pageIndexById.get(rule.target);
        if (targetIndex !== undefined && targetIndex >= 0) {
          for (let skipped = index + 1; skipped < targetIndex; skipped++) {
            skippedPageIds.push(fixture.pages[skipped]!.id);
          }
          index = targetIndex;
          continue;
        }
      }
    }

    index += 1;
  }

  return { presentedPageIds, presentedQuestionIds, skippedPageIds };
}

// --- Trial generation --------------------------------------------------------

function generateTrials(scenario: ScenarioName, seed: string, trialCount: number): TrialView[] {
  const base = (
    index: number,
    id: string,
    extra: Partial<TrialView>
  ): TrialView => ({
    index,
    id,
    stimulusOnsetTimestamp: null,
    responseTimestamp: null,
    reactionTimeMs: null,
    responseValue: null,
    correct: null,
    ...extra,
  });

  if (scenario === 'flanker') {
    return createFlankerTrials({ trialCount, congruentRatio: 0.5, seed }).map((trial, index) =>
      base(index, trial.id, {
        congruency: trial.congruency,
        expectedResponse: trial.expectedResponse,
        displayString: trial.displayString,
      })
    );
  }

  if (scenario === 'nback') {
    const stimulusSet = ['A', 'B', 'C', 'D'].map((letter) => ({
      kind: 'text' as const,
      text: letter,
    }));
    return createNBackTrials({
      n: 2,
      sequenceLength: trialCount,
      stimulusSet,
      targetRate: 0.3,
      seed,
    }).map((trial, index) =>
      base(index, trial.id, {
        isTarget: trial.isTarget,
        expectedResponse: trial.expectedResponse,
      })
    );
  }

  // Default + 'stroop' + 'control-flow' all seed a stroop trial list so the
  // trial-oriented injection API is always populated. (control-flow additionally
  // exposes its page walk via runControlFlow.)
  return createStroopTrials({ trialCount, congruentRatio: 0.5, seed }).map((trial, index) =>
    base(index, trial.id, {
      congruency: trial.congruency,
      expectedResponse: trial.expectedResponse,
      word: trial.word,
      inkColor: trial.inkColor,
    })
  );
}

// --- Harness core ------------------------------------------------------------

class ReactionHarness {
  scenario: ScenarioName = 'stroop';
  seed = DEFAULT_SEED;
  trials: TrialView[] = [];
  currentTrialIndex = 0;
  controlFlow: ControlFlowResult | null = null;
  completed = false;
  errors: string[] = [];

  loadScenario(name: ScenarioName, options: ScenarioOptions = {}): RuntimeDebugSnapshot {
    this.scenario = name;
    this.seed = options.seed ?? DEFAULT_SEED;
    const trialCount = options.trialCount ?? DEFAULT_TRIAL_COUNT;
    this.currentTrialIndex = 0;
    this.completed = false;
    this.errors = [];
    this.controlFlow = null;

    try {
      this.trials = generateTrials(this.scenario, this.seed, trialCount);
    } catch (error) {
      this.trials = [];
      this.errors.push(error instanceof Error ? error.message : String(error));
    }

    if (name === 'control-flow') {
      this.runControlFlow(options.answers ?? { q_gate: 1 });
    }

    return this.snapshot();
  }

  private trialAt(index: number): TrialView {
    const trial = this.trials[index];
    if (!trial) {
      throw new Error(`No trial at index ${index} (have ${this.trials.length})`);
    }
    return trial;
  }

  injectStimulusOnset(index: number, onsetTimestamp: number): void {
    const trial = this.trialAt(index);
    trial.stimulusOnsetTimestamp = onsetTimestamp;
  }

  injectResponse(index: number, responseTimestamp: number, value?: string): TrialView {
    const trial = this.trialAt(index);
    if (trial.stimulusOnsetTimestamp == null) {
      throw new Error(`Trial ${index} has no injected stimulus onset; call injectStimulusOnset first`);
    }
    trial.responseTimestamp = responseTimestamp;
    trial.reactionTimeMs = computeReactionTimeMs(trial.stimulusOnsetTimestamp, responseTimestamp);
    trial.responseValue = value ?? null;
    trial.correct =
      trial.expectedResponse == null || value == null
        ? null
        : value.toLowerCase() === trial.expectedResponse.toLowerCase();
    return trial;
  }

  injectTrial(
    index: number,
    onsetTimestamp: number,
    responseTimestamp: number,
    value?: string
  ): TrialView {
    this.injectStimulusOnset(index, onsetTimestamp);
    return this.injectResponse(index, responseTimestamp, value);
  }

  advance(): number {
    if (this.currentTrialIndex < this.trials.length - 1) {
      this.currentTrialIndex += 1;
    } else {
      this.currentTrialIndex = this.trials.length;
      this.completed = true;
    }
    return this.currentTrialIndex;
  }

  runControlFlow(answers: Record<string, unknown> = { q_gate: 1 }): ControlFlowResult {
    try {
      this.controlFlow = simulateControlFlow(buildControlFlowFixture(), answers);
    } catch (error) {
      this.errors.push(error instanceof Error ? error.message : String(error));
      this.controlFlow = { presentedPageIds: [], presentedQuestionIds: [], skippedPageIds: [] };
    }
    return this.controlFlow;
  }

  snapshot(): RuntimeDebugSnapshot {
    const currentTrial = this.trials[this.currentTrialIndex] ?? null;
    return {
      ready: true,
      scenario: this.scenario,
      seed: this.seed,
      // Deep-clone so a returned snapshot is an immutable point-in-time copy.
      trials: this.trials.map((trial) => ({ ...trial })),
      trialCount: this.trials.length,
      currentTrialIndex: this.currentTrialIndex,
      currentTrial: currentTrial ? { ...currentTrial } : null,
      stimulusOnsetTimestamp: currentTrial?.stimulusOnsetTimestamp ?? null,
      responseTimestamp: currentTrial?.responseTimestamp ?? null,
      reactionTimeMs: currentTrial?.reactionTimeMs ?? null,
      controlFlow: this.controlFlow ? { ...this.controlFlow } : null,
      completed: this.completed,
      errors: [...this.errors],
    };
  }
}

/**
 * Instantiate the harness and expose it on `window.__QDESIGNER_RUNTIME_DEBUG__`.
 * The caller (the guarded route) must only invoke this when the route is
 * enabled, so the debug global never exists in a production build.
 *
 * @returns a disposer that removes the global.
 */
export function installReactionHarness(
  initialScenario: ScenarioName = 'stroop',
  options: ScenarioOptions = {}
): () => void {
  if (typeof window === 'undefined') {
    return () => {};
  }

  const harness = new ReactionHarness();

  const api: RuntimeDebugApi = {
    // Snapshot fields are refreshed on every read via getters so tests never
    // observe a stale value between injections.
    get ready() {
      return true;
    },
    get scenario() {
      return harness.scenario;
    },
    get seed() {
      return harness.seed;
    },
    get trials() {
      return harness.snapshot().trials;
    },
    get trialCount() {
      return harness.trials.length;
    },
    get currentTrialIndex() {
      return harness.currentTrialIndex;
    },
    get currentTrial() {
      return harness.snapshot().currentTrial;
    },
    get stimulusOnsetTimestamp() {
      return harness.snapshot().stimulusOnsetTimestamp;
    },
    get responseTimestamp() {
      return harness.snapshot().responseTimestamp;
    },
    get reactionTimeMs() {
      return harness.snapshot().reactionTimeMs;
    },
    get controlFlow() {
      return harness.controlFlow ? { ...harness.controlFlow } : null;
    },
    get completed() {
      return harness.completed;
    },
    get errors() {
      return [...harness.errors];
    },
    loadScenario: (name, opts) => harness.loadScenario(name, opts),
    injectStimulusOnset: (index, onset) => harness.injectStimulusOnset(index, onset),
    injectResponse: (index, response, value) => harness.injectResponse(index, response, value),
    injectTrial: (index, onset, response, value) =>
      harness.injectTrial(index, onset, response, value),
    advance: () => harness.advance(),
    runControlFlow: (answers) => harness.runControlFlow(answers),
    snapshot: () => harness.snapshot(),
  };

  harness.loadScenario(initialScenario, options);
  (window as RuntimeWindow).__QDESIGNER_RUNTIME_DEBUG__ = api;

  return () => {
    delete (window as RuntimeWindow).__QDESIGNER_RUNTIME_DEBUG__;
  };
}
