// This file will be auto-generated by Supabase CLI
// Run: pnpm db:types to generate types from your database schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Tables will be defined here after running migrations
    }
    Views: {
      // Views will be defined here
    }
    Functions: {
      // Functions will be defined here
    }
    Enums: {
      // Enums will be defined here
    }
    CompositeTypes: {
      // Composite types will be defined here
    }
  }
}