-- 00021_fillout_dual_policies.sql
--
-- Closes the broken-interval opened by P6.2 for fillout-path tables.
--
-- Two things this migration does:
--
-- 1) Drop RLS on `questionnaire_definitions`. ADR 0012 records the
--    decision: GET /api/questionnaires/by-code/{code} is intentional
--    public-anonymous read; admin-side reads walk the still-RLS-bound
--    `projects` chain. RLS adds nothing here and breaks INSERTs until
--    a dual-path scheme is designed for it (out of scope; the table
--    is keyed by code, not by session).
--
-- 2) Dual-path SELECT/INSERT/UPDATE/DELETE policies on `sessions`,
--    `responses`, `interaction_events`, `session_variables`. ADR 0012
--    records the design: two transaction-local GUCs (`app.user_id`
--    set by the existing `set_rls_context` middleware,
--    `app.session_id` set by the new `set_fillout_rls_context`
--    sibling for fillout traffic) admit reads/writes via OR semantics.
--
-- Bootstrap admission: anonymous `POST /api/sessions` cannot pre-bind
-- `app.session_id` to the row being inserted (the id is generated by
-- the INSERT). The INSERT policy on `sessions` therefore admits a
-- third "true anonymous bootstrap" branch:
-- `current_app_user_id() IS NULL AND current_app_session_id() IS NULL`.
-- UPDATE/DELETE do NOT carry this branch — you have to already be
-- bound to a session to mutate it.
--
-- Threat-model note (recap of ADR 0012): session URLs remain
-- credentials. Anyone who knows the URL can read the session's data
-- through the API. RLS enforces "a request bound to app.session_id =
-- X reads only session X's data", but doesn't change the URL-as-
-- credential property.

-- ── Helper function ──────────────────────────────────────────────────

-- Mirror of `current_app_user_id()` (00014) for the fillout GUC.
CREATE OR REPLACE FUNCTION public.current_app_session_id()
RETURNS uuid
LANGUAGE sql
STABLE
AS $$
    SELECT NULLIF(current_setting('app.session_id', true), '')::uuid;
$$;

-- ── questionnaire_definitions: RLS exits (ADR 0012) ──────────────────

ALTER TABLE public.questionnaire_definitions DISABLE ROW LEVEL SECURITY;

-- 00014's questionnaire_definitions_select policy is left declared but
-- inert (the table no longer enforces it). Dropping it is harmless
-- noise; leaving it lets a future re-enable resume the prior shape.

-- ── projects: admit anonymous SELECT for rows that own a published
--    questionnaire (the by-code endpoint reads this) ─────────────────
--
-- GET /api/questionnaires/by-code/{code} returns the questionnaire
-- joined to its project (so the fillout client can render project
-- name + start/end dates). The 00014 projects_select policy admits
-- only authenticated org members; anonymous fillout has no GUC and
-- gets zero rows from the JOIN. Adding this second SELECT policy
-- (OR-merged with 00014's existing one) admits the JOIN target when
-- the project owns at least one published questionnaire.
--
-- Threat trade: any project that publishes a questionnaire becomes
-- SELECT-readable by id (anonymous, GUC-less). The exposed columns
-- (name, dates) are exactly what the public by-code endpoint already
-- returns. Cross-tenant *unpublished* project data still hides
-- behind the existing 00014 policy.

DROP POLICY IF EXISTS projects_select_via_published_questionnaire ON public.projects;
CREATE POLICY projects_select_via_published_questionnaire ON public.projects
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.questionnaire_definitions qd
            WHERE qd.project_id = projects.id
              AND qd.status = 'published'
              AND qd.deleted_at IS NULL
        )
    );

-- ── sessions: dual-path policies ─────────────────────────────────────

DROP POLICY IF EXISTS sessions_select ON public.sessions;
DROP POLICY IF EXISTS sessions_select_dual ON public.sessions;
DROP POLICY IF EXISTS sessions_insert_dual ON public.sessions;
DROP POLICY IF EXISTS sessions_update_dual ON public.sessions;
DROP POLICY IF EXISTS sessions_delete_dual ON public.sessions;

CREATE POLICY sessions_select_dual ON public.sessions
    FOR SELECT USING (
        public.is_super_admin()
        OR (public.current_app_user_id() IS NOT NULL
            AND sessions.user_id = public.current_app_user_id())
        OR (public.current_app_session_id() IS NOT NULL
            AND sessions.id = public.current_app_session_id())
        OR EXISTS (
            -- Authenticated org members see sessions for questionnaires
            -- in their org (read-only admin path; unchanged 00014 chain).
            SELECT 1
            FROM public.questionnaire_definitions qd
            JOIN public.projects p ON p.id = qd.project_id
            JOIN public.organization_members om
                 ON om.organization_id = p.organization_id
            WHERE qd.id = sessions.questionnaire_id
              AND om.user_id = public.current_app_user_id()
              AND om.status = 'active'
        )
    );

CREATE POLICY sessions_insert_dual ON public.sessions
    FOR INSERT WITH CHECK (
        public.is_super_admin()
        OR (public.current_app_user_id() IS NOT NULL
            AND sessions.user_id = public.current_app_user_id())
        OR (public.current_app_session_id() IS NOT NULL
            AND sessions.id = public.current_app_session_id())
        -- Bootstrap branch: anonymous session creation (no JWT, no
        -- session-bound GUC) is the entry point and cannot self-
        -- reference. The session URL becomes the credential immediately
        -- afterwards.
        OR (public.current_app_user_id() IS NULL
            AND public.current_app_session_id() IS NULL)
    );

CREATE POLICY sessions_update_dual ON public.sessions
    FOR UPDATE
    USING (
        public.is_super_admin()
        OR (public.current_app_user_id() IS NOT NULL
            AND sessions.user_id = public.current_app_user_id())
        OR (public.current_app_session_id() IS NOT NULL
            AND sessions.id = public.current_app_session_id())
    )
    WITH CHECK (
        public.is_super_admin()
        OR (public.current_app_user_id() IS NOT NULL
            AND sessions.user_id = public.current_app_user_id())
        OR (public.current_app_session_id() IS NOT NULL
            AND sessions.id = public.current_app_session_id())
    );

CREATE POLICY sessions_delete_dual ON public.sessions
    FOR DELETE USING (
        public.is_super_admin()
        OR (public.current_app_user_id() IS NOT NULL
            AND sessions.user_id = public.current_app_user_id())
        OR (public.current_app_session_id() IS NOT NULL
            AND sessions.id = public.current_app_session_id())
    );

-- ── responses / interaction_events / session_variables ──────────────
--
-- Joined-through-sessions: the row is admitted iff the session it
-- references is admitted under the dual-path SELECT predicate.

DROP POLICY IF EXISTS responses_select ON public.responses;
DROP POLICY IF EXISTS responses_select_dual ON public.responses;
DROP POLICY IF EXISTS responses_insert_dual ON public.responses;
DROP POLICY IF EXISTS responses_update_dual ON public.responses;
DROP POLICY IF EXISTS responses_delete_dual ON public.responses;

CREATE POLICY responses_select_dual ON public.responses
    FOR SELECT USING (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = responses.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
        OR EXISTS (
            SELECT 1
            FROM public.sessions s
            JOIN public.questionnaire_definitions qd ON qd.id = s.questionnaire_id
            JOIN public.projects p ON p.id = qd.project_id
            JOIN public.organization_members om
                 ON om.organization_id = p.organization_id
            WHERE s.id = responses.session_id
              AND om.user_id = public.current_app_user_id()
              AND om.status = 'active'
        )
    );

CREATE POLICY responses_insert_dual ON public.responses
    FOR INSERT WITH CHECK (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = responses.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
    );

CREATE POLICY responses_update_dual ON public.responses
    FOR UPDATE
    USING (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = responses.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
    )
    WITH CHECK (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = responses.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
    );

CREATE POLICY responses_delete_dual ON public.responses
    FOR DELETE USING (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = responses.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
    );

-- interaction_events ─────────────────────────────────────────────────

DROP POLICY IF EXISTS interaction_events_select ON public.interaction_events;
DROP POLICY IF EXISTS interaction_events_select_dual ON public.interaction_events;
DROP POLICY IF EXISTS interaction_events_insert_dual ON public.interaction_events;
DROP POLICY IF EXISTS interaction_events_update_dual ON public.interaction_events;
DROP POLICY IF EXISTS interaction_events_delete_dual ON public.interaction_events;

CREATE POLICY interaction_events_select_dual ON public.interaction_events
    FOR SELECT USING (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = interaction_events.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
        OR EXISTS (
            SELECT 1
            FROM public.sessions s
            JOIN public.questionnaire_definitions qd ON qd.id = s.questionnaire_id
            JOIN public.projects p ON p.id = qd.project_id
            JOIN public.organization_members om
                 ON om.organization_id = p.organization_id
            WHERE s.id = interaction_events.session_id
              AND om.user_id = public.current_app_user_id()
              AND om.status = 'active'
        )
    );

CREATE POLICY interaction_events_insert_dual ON public.interaction_events
    FOR INSERT WITH CHECK (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = interaction_events.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
    );

CREATE POLICY interaction_events_update_dual ON public.interaction_events
    FOR UPDATE
    USING (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = interaction_events.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
    )
    WITH CHECK (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = interaction_events.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
    );

CREATE POLICY interaction_events_delete_dual ON public.interaction_events
    FOR DELETE USING (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = interaction_events.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
    );

-- session_variables ──────────────────────────────────────────────────

DROP POLICY IF EXISTS session_variables_select ON public.session_variables;
DROP POLICY IF EXISTS session_variables_select_dual ON public.session_variables;
DROP POLICY IF EXISTS session_variables_insert_dual ON public.session_variables;
DROP POLICY IF EXISTS session_variables_update_dual ON public.session_variables;
DROP POLICY IF EXISTS session_variables_delete_dual ON public.session_variables;

CREATE POLICY session_variables_select_dual ON public.session_variables
    FOR SELECT USING (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = session_variables.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
        OR EXISTS (
            SELECT 1
            FROM public.sessions s
            JOIN public.questionnaire_definitions qd ON qd.id = s.questionnaire_id
            JOIN public.projects p ON p.id = qd.project_id
            JOIN public.organization_members om
                 ON om.organization_id = p.organization_id
            WHERE s.id = session_variables.session_id
              AND om.user_id = public.current_app_user_id()
              AND om.status = 'active'
        )
    );

CREATE POLICY session_variables_insert_dual ON public.session_variables
    FOR INSERT WITH CHECK (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = session_variables.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
    );

CREATE POLICY session_variables_update_dual ON public.session_variables
    FOR UPDATE
    USING (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = session_variables.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
    )
    WITH CHECK (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = session_variables.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
    );

CREATE POLICY session_variables_delete_dual ON public.session_variables
    FOR DELETE USING (
        public.is_super_admin()
        OR EXISTS (
            SELECT 1 FROM public.sessions s
            WHERE s.id = session_variables.session_id
              AND (
                (public.current_app_user_id() IS NOT NULL
                 AND s.user_id = public.current_app_user_id())
                OR (public.current_app_session_id() IS NOT NULL
                    AND s.id = public.current_app_session_id())
              )
        )
    );
