//! Effective variable identities available to portable behavior references.
//! Authored declarations remain unchanged; generated runtime outputs are lookup
//! metadata only and are never written into the exported variable registry.
use super::{error, pointer_segment, DefinitionDiagnostic};
use serde_json::{json, Value};
use std::collections::{BTreeMap, BTreeSet};

pub(super) struct Catalogue {
    declarations: BTreeMap<String, Value>,
    iterations: BTreeMap<String, (usize, String)>,
}

impl Catalogue {
    fn iteration_base(&self, name: &str) -> Option<String> {
        let (question, tail) = name.rsplit_once("__")?;
        let (iteration, suffix) = tail
            .split_once('_')
            .map_or((tail, ""), |(index, suffix)| (index, suffix));
        let index = iteration.parse::<usize>().ok()?;
        if index.to_string() != iteration || index >= self.iterations.get(question)?.0 {
            return None;
        }
        match suffix {
            "" => Some(question.to_owned()),
            "value" | "time" | "rt" | "correct" | "onset" => Some(format!("{question}_{suffix}")),
            _ => None,
        }
    }

    pub(super) fn get(&self, name: &str) -> Option<&Value> {
        self.declarations.get(name).or_else(|| {
            self.iteration_base(name)
                .and_then(|base| self.declarations.get(&base))
        })
    }
}

fn array(value: &Value) -> &[Value] {
    value.as_array().map(Vec::as_slice).unwrap_or_default()
}

fn add(catalogue: &mut BTreeMap<String, Value>, id: &str, name: &str, kind: &str) {
    let declaration = json!({"id":id,"name":name,"type":kind});
    catalogue
        .entry(id.to_owned())
        .or_insert_with(|| declaration.clone());
    catalogue.entry(name.to_owned()).or_insert(declaration);
}

fn reserve(
    names: &mut BTreeMap<String, String>,
    name: String,
    path: String,
    diagnostics: &mut Vec<DefinitionDiagnostic>,
) {
    if let Some(previous) = names.insert(name.clone(), path.clone()) {
        if previous != path {
            let mut diagnostic = error(
                "QDEF_DUPLICATE_ID",
                path,
                format!("Runtime identity '{name}' is also generated by another declaration."),
                None,
            );
            diagnostic.related_paths.push(previous);
            diagnostics.push(diagnostic);
        }
    }
}

pub(super) fn build(value: &Value, diagnostics: &mut Vec<DefinitionDiagnostic>) -> Catalogue {
    let mut catalogue = BTreeMap::new();
    let mut reserved = BTreeMap::new();
    let mut iterations: BTreeMap<String, (usize, String)> = BTreeMap::new();
    let mut named_outputs = BTreeMap::new();
    if let Some(variables) = value["variables"].as_object() {
        for (id, variable) in variables {
            catalogue.insert(id.clone(), variable.clone());
            catalogue.insert(
                variable["name"].as_str().unwrap_or(id).to_owned(),
                variable.clone(),
            );
        }
    }
    if let Some(questions) = value["questions"].as_object() {
        for (id, question) in questions {
            reserve(
                &mut reserved,
                id.clone(),
                format!("/questions/{}", pointer_segment(id)),
                diagnostics,
            );
            for suffix in ["value", "time", "rt", "correct", "onset"] {
                reserve(
                    &mut reserved,
                    format!("{id}_{suffix}"),
                    format!("/questions/{}", pointer_segment(id)),
                    diagnostics,
                );
            }
            add(
                &mut catalogue,
                &format!("{id}_value"),
                id,
                answer_type(question),
            );
            for (suffix, kind) in [
                ("time", "time"),
                ("rt", "reaction_time"),
                ("correct", "boolean"),
                ("onset", "stimulus_onset"),
            ] {
                let name = format!("{id}_{suffix}");
                add(&mut catalogue, &name, &name, kind);
            }
        }
    }
    for (name, kind) in [
        ("participantId", "string"),
        ("currentPage", "number"),
        ("totalPages", "number"),
        ("waveIndex", "number"),
        ("seriesElapsedDays", "number"),
        ("quotaCell", "string"),
        ("eligible", "boolean"),
        ("theta", "number"),
        ("thetaSE", "number"),
        ("adaptiveItemsAdministered", "number"),
    ] {
        reserve(
            &mut reserved,
            name.to_owned(),
            "/settings".to_owned(),
            diagnostics,
        );
        reserve(
            &mut reserved,
            format!("_{name}"),
            "/settings".to_owned(),
            diagnostics,
        );
        add(&mut catalogue, &format!("_{name}"), name, kind);
    }
    if !array(&value["settings"]["experimentalDesign"]["conditions"]).is_empty() {
        for name in [
            "condition",
            "_condition",
            "conditionIndex",
            "_conditionIndex",
        ] {
            reserve(
                &mut reserved,
                name.to_owned(),
                "/settings/experimentalDesign".to_owned(),
                diagnostics,
            );
        }
        add(&mut catalogue, "_condition", "condition", "string");
        add(
            &mut catalogue,
            "_conditionIndex",
            "conditionIndex",
            "number",
        );
    }
    if value["variables"]
        .as_object()
        .is_some_and(|vars| vars.values().any(|v| v.get("server").is_some()))
    {
        for name in ["serverDataAsOf", "_serverDataAsOf"] {
            reserve(
                &mut reserved,
                name.to_owned(),
                "/variables".to_owned(),
                diagnostics,
            );
        }
        add(
            &mut catalogue,
            "_serverDataAsOf",
            "serverDataAsOf",
            "string",
        );
    }
    // Loop context is cleared even for non-loop items. Its value can be
    // heterogeneous; identity validation must not invent a fixed payload type.
    add(&mut catalogue, "loopValue", "loopValue", "dynamic");
    for name in ["loopValue", "_iterationIndex", "_iterationCount"] {
        reserve(
            &mut reserved,
            name.to_owned(),
            "/structure".to_owned(),
            diagnostics,
        );
    }
    for name in ["_iterationIndex", "_iterationCount"] {
        add(&mut catalogue, name, name, "number");
    }
    for (page_index, page) in array(&value["structure"]["pages"]).iter().enumerate() {
        for (block_index, block) in array(&page["blocks"]).iter().enumerate() {
            let path = format!("/structure/pages/{page_index}/blocks/{block_index}");
            if block["type"] == "adaptive" {
                if let Some(name) = block["adaptive"]["thetaReportVariable"].as_str() {
                    named_outputs.insert(
                        name.to_owned(),
                        format!("{path}/adaptive/thetaReportVariable"),
                    );
                    add(&mut catalogue, name, name, "number");
                }
            }
            if let Some(loop_config) = block.get("loop") {
                if let Some(name) = loop_config["loopVariableName"]
                    .as_str()
                    .filter(|s| !s.is_empty())
                {
                    if name != "loopValue" {
                        named_outputs
                            .insert(name.to_owned(), format!("{path}/loop/loopVariableName"));
                    }
                    add(&mut catalogue, name, name, "dynamic");
                }
                let cap = loop_config["maxIterations"]
                    .as_f64()
                    .filter(|n| *n > 0.0)
                    .map_or(500, |n| n.floor().min(500.0) as usize);
                let count = if matches!(
                    loop_config["source"]["type"].as_str(),
                    Some("answer" | "variable")
                ) {
                    cap
                } else {
                    cap.min(array(&loop_config["values"]).len())
                };
                for question in array(&block["questionIds"])
                    .iter()
                    .filter_map(Value::as_str)
                {
                    iterations
                        .entry(question.to_owned())
                        .and_modify(|entry| {
                            if count > entry.0 {
                                *entry = (count, format!("{path}/loop"));
                            }
                        })
                        .or_insert((count, format!("{path}/loop")));
                }
            }
        }
    }
    for (index, scale) in array(&value["settings"]["scoring"]["scales"])
        .iter()
        .enumerate()
    {
        let Some(id) = scale["id"].as_str() else {
            continue;
        };
        let name = format!("score.{id}");
        let path = format!("/settings/scoring/scales/{index}/id");
        reserve(&mut reserved, name.clone(), path.clone(), diagnostics);
        add(&mut catalogue, &name, &name, "object");
        for field in [
            "value",
            "z",
            "tScore",
            "stanine",
            "percentile",
            "itemsAnswered",
            "itemsExpected",
            "band",
        ] {
            let name = format!("score.{id}.{field}");
            reserve(&mut reserved, name.clone(), path.clone(), diagnostics);
            add(
                &mut catalogue,
                &name,
                &name,
                if field == "band" { "string" } else { "number" },
            );
        }
    }
    let result = Catalogue {
        declarations: catalogue,
        iterations,
    };
    let mut conflicting_paths = BTreeSet::new();
    for (name, path) in &reserved {
        if result.iteration_base(name).is_some() && conflicting_paths.insert(path) {
            let mut diagnostic = error(
                "QDEF_DUPLICATE_ID",
                path.clone(),
                format!("Runtime identity '{name}' conflicts with a loop iteration output."),
                None,
            );
            if let Some((question, _)) = name.rsplit_once("__") {
                if let Some((_, loop_path)) = result.iterations.get(question) {
                    diagnostic.related_paths.push(loop_path.clone());
                }
            }
            diagnostics.push(diagnostic);
        }
    }
    for (name, path) in &named_outputs {
        if reserved.contains_key(name) || result.iteration_base(name).is_some() {
            diagnostics.push(error(
                "QDEF_DUPLICATE_ID",
                path.clone(),
                format!("Named output '{name}' conflicts with a generated runtime identity."),
                None,
            ));
        }
    }
    if let Some(variables) = value["variables"].as_object() {
        for (id, variable) in variables {
            let name = variable["name"].as_str().unwrap_or(id);
            if (named_outputs.contains_key(id) || named_outputs.contains_key(name)) && id != name {
                diagnostics.push(error("QDEF_DUPLICATE_ID", format!("/variables/{}/name", pointer_segment(id)), "A declared writable loop or adaptive output must use the same registry identity and name.", None));
            }
            for (identifier, suffix) in [(id.as_str(), ""), (name, "/name")] {
                if reserved.contains_key(identifier) || result.iteration_base(identifier).is_some()
                {
                    diagnostics.push(error("QDEF_DUPLICATE_ID", format!("/variables/{}{suffix}", pointer_segment(id)), format!("Variable identity '{identifier}' is generated by the participant runtime."), Some("Choose an authored variable identity that does not overwrite a system or question output.")));
                    break;
                }
            }
        }
    }
    result
}

fn answer_type(question: &Value) -> &'static str {
    if let Some(kind) = question["responseType"]["type"].as_str() {
        return match kind {
            "number" | "scale" => "number",
            "multiple" => "array",
            "single" => {
                let options: Vec<_> = array(&question["responseType"]["options"])
                    .iter()
                    .filter_map(|v| v.get("value").filter(|v| !v.is_null()))
                    .collect();
                if !options.is_empty() && options.iter().all(|v| v.is_number()) {
                    "number"
                } else if !options.is_empty() && options.iter().all(|v| v.is_boolean()) {
                    "boolean"
                } else {
                    "string"
                }
            }
            "text" | "keypress" | "none" => "string",
            _ => "object",
        };
    }
    match question["type"].as_str().unwrap_or_default() {
        "number-input" | "rating" | "scale" => "number",
        "ranking" => "array",
        "matrix" => "object",
        "multiple-choice"
            if question["response"]["type"] == "multiple"
                || question["config"]["responseType"]["type"] == "multiple"
                || question["display"]["responseType"] == "multiple" =>
        {
            "array"
        }
        _ => "string",
    }
}
